### 00. Pytorch fundementals

In [184]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

print(torch.__version__)

2.6.0+cu126


## Introduction to tensors

### Creating tensors

Pytorch tensors are created by `torch.tensor()`

In [185]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

# Number of dimensions of a tensor
print(scalar.ndim)

# Get tensor back as python int 
print(scalar.item())

tensor(7)
0
7


In [186]:
# Vector
vector = torch.tensor([4,432,3])
print(vector)
# Dimensions
print(vector.ndim)
# Shape
print(vector.shape)

tensor([  4, 432,   3])
1
torch.Size([3])


In [187]:
# Matrix, often uppercase nomenclature
MATRIX = torch.tensor([[7,8], [23,3]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [188]:
# Tensor, ofter uppercase nomenclature
TENSOR = torch.tensor([[[23,3,23], [2,3,4]],
                        [[23,32,3], [32,3,23]]])
print(TENSOR.shape)
print(TENSOR.ndim)
print(TENSOR[0])

torch.Size([2, 2, 3])
3
tensor([[23,  3, 23],
        [ 2,  3,  4]])


### Random tensors

Random tensors are important because the way many neural networks work is that they start with random numbers, and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update numbers...`

In [189]:
#Creating a random tensor of size (2,3,4)
random_tensor = torch.rand(2,3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.4099, 0.6578, 0.3139, 0.7956],
         [0.8734, 0.5901, 0.8618, 0.8661],
         [0.9594, 0.9358, 0.7242, 0.8604]],

        [[0.5097, 0.4726, 0.6141, 0.9994],
         [0.9468, 0.6138, 0.3517, 0.0536],
         [0.0310, 0.5128, 0.3997, 0.3436]]])
3
torch.Size([2, 3, 4])


In [190]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height, width, color channels (R, G, B)
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)

torch.Size([3, 224, 224]) 3


### Zeros and ones

In [191]:
# Create a tensor of all zeros 
zeros = torch.zeros(size = (3,4))
print(zeros)
print(zeros * random_tensor)

# Create a tensor of all ones
ones = torch.ones(size = (3,4), dtype=float)
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
torch.float64


### Create a range of tensors and tensor-like

In [192]:
# Use torch.arange
one_to_eleven =  torch.arange(start=39, end = 3234, step =44)
print(one_to_eleven)

# Creating tensors-like (the same shape as the inputted tensor)
ten_zeros = torch.zeros_like(input = one_to_eleven)
print(ten_zeros)


tensor([  39,   83,  127,  171,  215,  259,  303,  347,  391,  435,  479,  523,
         567,  611,  655,  699,  743,  787,  831,  875,  919,  963, 1007, 1051,
        1095, 1139, 1183, 1227, 1271, 1315, 1359, 1403, 1447, 1491, 1535, 1579,
        1623, 1667, 1711, 1755, 1799, 1843, 1887, 1931, 1975, 2019, 2063, 2107,
        2151, 2195, 2239, 2283, 2327, 2371, 2415, 2459, 2503, 2547, 2591, 2635,
        2679, 2723, 2767, 2811, 2855, 2899, 2943, 2987, 3031, 3075, 3119, 3163,
        3207])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])


### Tensor datatypes

**Note:** it is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not the right shape
3. Tensors not on rigth device

In [193]:
# Float_32 tensor
# Look at datatypes torch.dtypes
float_32_tensor = torch.tensor([3.0,6.0,9.0], # 3 most important params
                               dtype=torch.float32, # data type of your sensor
                             device=None,# which device your tensor is o
                             requires_grad=False) # Wheather or not to track gradients
print(float_32_tensor.dtype)

# Converting 
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)

torch.float32
torch.float16


In [194]:
int_32_tensor = torch.tensor([3,2,32], dtype=torch.int32)
print(int_32_tensor)
print(float_32_tensor * int_32_tensor)

long_tensor = torch.tensor([3,23,3], dtype=torch.long)
print(float_32_tensor * long_tensor)

tensor([ 3,  2, 32], dtype=torch.int32)
tensor([  9.,  12., 288.])
tensor([  9., 138.,  27.])


### Getting information from tensors (tensor attributes)

device - .device

data type - .dtype

shape - .shape

In [195]:
some_tensor = torch.rand(size=(3,2), device="cuda")
print(some_tensor)
print(f"Device: {some_tensor.device}\nData type: {some_tensor.dtype}\nShape: {some_tensor.shape}")


tensor([[0.6401, 0.0332],
        [0.3768, 0.2720],
        [0.5560, 0.9709]], device='cuda:0')
Device: cuda:0
Data type: torch.float32
Shape: torch.Size([3, 2])


### Manipulating tensors (tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element-wise)
* Multiplication (Matrix)
* Division

In [196]:
# Create a tensor, and add 10
tensor = torch.tensor([1,2,3])
tensor += 10
print(tensor)
print(tensor * 10) 

# Subtract
print(tensor -10)

# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([11, 12, 13])
tensor([110, 120, 130])
tensor([1, 2, 3])


tensor([110, 120, 130])

## Matrix multiplication

3 main ways of performing multiplication in deep learning:
* Element-wise multiplication
* Matrix multiplication

In [197]:
# Element wise 
print(tensor, "*", tensor , "=", tensor*tensor)

# Matrix multiplication
print(tensor @ tensor)
torch.matmul(tensor, tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13]) = tensor([121, 144, 169])
tensor(434)


tensor(434)

In [198]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]

CPU times: total: 31.2 ms
Wall time: 0 ns


In [199]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(434)

##### Matrix multiplication rules
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the outer dimensions

In [200]:
# Example
print((torch.rand(3,2) @ torch.rand(2,3)).shape) # Works (inner dimensions are the same), dim is 3x3
torch.rand(3,2) @torch.rand(3,3) # Doesn't work

torch.Size([3, 3])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x3)

In [201]:
# Shapes for matrix multiplications
# Transposition
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# tensor.T for to get the transpose of the tensor
print(tensor_A.shape)
print(tensor_A.T.shape)
print(tensor_A.T)
print(tensor_A.T @ tensor_B)

torch.Size([3, 2])
torch.Size([2, 3])
tensor([[1, 3, 5],
        [2, 4, 6]])
tensor([[ 76, 103],
        [100, 136]])


### Agregation functions: min, max, mean, sum, etc.


In [202]:
tensor = torch.arange(0,100,10)

# Find the min
torch.min(tensor), tensor.min()

# Find teh max
torch.max(tensor), tensor.max()

# Find the mean, we have to convert to float, since the torch.mean() requires the float data type
torch.mean(tensor.type(dtype=torch.float32)), tensor.type(dtype=torch.float32).mean()

# Find the sum
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

In [203]:
# Postional min and max (find the index of the minimum value in the tensor)
tensor = torch.tensor([[3,23,52,2,0,32342], [3,23,32,23,32,-23]])
tensor.argmin()
tensor.argmax()

tensor(5)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes the input tensor to the defined shape
* View - return a view of and input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack - vertical), (hstack - horizontal)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - REturn a view of the input with dimensions permuted (swapped) in a certain way

In [235]:
x = torch.arange(1,10)
print(x, x.shape)

# Reshaping, add an extra dimension
x_reshaped = x.reshape(1,3,3) # The dimensions have to be appropriate for the amount of elements
print(x_reshaped)

# Change the view
z = x.view(1,9) # Z has the same reference to x, if we change z we also change x
print(z, z.shape)
z[:,0] = 500
print(z,x)

# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1) # In which dimension do we stack together
print(x_stacked)

# Squeeze and Unsqueeze
x_squeezed = torch.squeeze(x)
print(x_squeezed)
x_unsqueezed = torch.unsqueeze(x, 1)
print(x_unsqueezed)



tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[500,   2,   3,   4,   5,   6,   7,   8,   9]]) tensor([500,   2,   3,   4,   5,   6,   7,   8,   9])
tensor([[500, 500, 500, 500],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5],
        [  6,   6,   6,   6],
        [  7,   7,   7,   7],
        [  8,   8,   8,   8],
        [  9,   9,   9,   9]])
tensor([500,   2,   3,   4,   5,   6,   7,   8,   9])
tensor([[500],
        [  2],
        [  3],
        [  4],
        [  5],
        [  6],
        [  7],
        [  8],
        [  9]])
